version: "3.2"
services:

  frontend:
    container_name: ziyou-front
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
    volumes:
      - ./frontend/:/app
    command: sh -c "npm run build && http-server dist"
    ports:
      - 8080:8080

  backend:
    container_name: ziyou-back
    restart: always
    image: node:alpine
    stdin_open: true
    tty: true
    working_dir: /api
    volumes:
      - ./backend/:/api
    command: sh -c "npm run build && npm start"
    ports:
      - 5000:5000
    expose:
      - "5000"

volumes:
  my-db: